Update doc

diff --git a/src/scripts/jnt_tutorial.init b/src/scripts/jnt_tutorial.init
--- a/src/scripts/jnt_tutorial.init
+++ b/src/scripts/jnt_tutorial.init
@@ -1,38 +1,57 @@
 #!/bin/sh
 
 ### BEGIN INIT INFO
-# Provides:             jnt_rantanplan
+# Provides:             jnt_tutorial
 # Required-Start:       $remote_fs $syslog $network
 # Required-Stop:        $remote_fs $syslog $network
 # Default-Start:        2 3 4 5
 # Default-Stop:         0 1 6
-# Short-Description:    Janitoo rantanplan
-# Description:          Janitoo rantanplan appliance server
+# Short-Description:    Janitoo tutorial
+# Description:          Janitoo tutorial appliance server
 #
 ### END INIT INFO
 
-NAME="jnt_rantanplan"
+NAME="jnt_tutorial"
 
 # Internal script
 # You should not update lines below
-# Version 0.0.7
-set -e
-
-DAEMON="/usr/bin/${NAME}"
-test -x "${DAEMON}" || DAEMON="/usr/sbin/${NAME}"
-test -x "${DAEMON}" || DAEMON="/usr/local/bin/${NAME}"
-
-CONFFILE="/etc/janitoo/${NAME}.conf"
-test -f "${CONFFILE}" || CONFFILE="/opt/janitoo/etc/${NAME}.conf"
-
-test -x "${DAEMON}" || echo "Can't find ${DAEMON}" && exit 0
-test -f "${CONFFILE}" || echo "Can't find ${CONFFILE}" && exit 0
-
+# Version 0.0.9
 PATH="/sbin:/bin:/usr/sbin:/usr/bin"
 
-PIDFILE="/opt/janitoo/run/${NAME}.pid"
-test -d "/run/janitoo" && PIDFILE="/run/janitoo/${NAME}.pid"
-test -d "/var/run/janitoo" && PIDFILE="/var/run/janitoo/${NAME}.pid"
+DAEMON="/usr/bin/${NAME}"
+if [ ! -x "$DAEMON" ]; then
+    DAEMON="/usr/sbin/${NAME}"
+fi
+if [ ! -x "$DAEMON" ]; then
+    DAEMON="/usr/local/bin/${NAME}"
+fi
+if [ ! -x "$DAEMON" ]; then
+    echo "Can't find daemon ${DAEMON}"
+    exit 1
+fi
+
+CONFFILE="/etc/janitoo/${NAME}.conf"
+if [ ! -f "$CONFFILE" ]; then
+    CONFFILE="/opt/janitoo/etc/${NAME}.conf"
+fi
+if [ ! -f "$CONFFILE" ]; then
+   echo "Can't find configuration ${CONFFILE}"
+   exit 2
+fi
+
+PIDDIR="/run/janitoo"
+if [ ! -d "$PIDDIR" ]; then
+   PIDDIR="/var/run/janitoo"
+fi
+if [ ! -d "$PIDDIR" ]; then
+   PIDDIR="/opt/janitoo/run"
+fi
+if [ ! -d "$PIDDIR" ]; then
+   echo "Can't find pid directory ${PIDDIR}"
+   exit 3
+fi
+
+PIDFILE="/${PIDDIR}/${NAME}.pid"
 
 case "${1}" in
     start)
@@ -85,7 +104,7 @@ case "${1}" in
         ;;
 
     *)
-        echo "Usage: /etc/init.d/${NAME} {start|stop|restart|reload|status|kill}"
+        echo "Usage: sudo service ${NAME} {start|stop|restart|reload|status|kill}"
         exit 1
         ;;
 esac
